name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_USERNAME }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push MongoDB image
        run: |
          docker build -t your-dockerhub-username/mongodb:latest ./mongodb
          docker push your-dockerhub-username/mongodb:latest

      - name: Build and push Backend image
        run: |
          docker build -t your-dockerhub-username/backend:latest ./backend
          docker push your-dockerhub-username/backend:latest

      - name: Build and push Frontend image
        run: |
          docker build -t your-dockerhub-username/frontend:latest ./frontend
          docker push your-dockerhub-username/frontend:latest
