name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push frontend Docker image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build --platform linux/amd64 --tag yourusername/frontend:latest ./frontend
          docker tag yourusername/frontend:latest yourusername/frontend:${{ github.sha }}
          docker push yourusername/frontend:latest
          docker push yourusername/frontend:${{ github.sha }}

      - name: Build and push backend Docker image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build --platform linux/amd64 --tag yourusername/backend:latest ./backend
          docker tag yourusername/backend:latest yourusername/backend:${{ github.sha }}
          docker push yourusername/backend:latest
          docker push yourusername/backend:${{ github.sha }}
